import json

data = {
    "chart_html": "<script src=\\\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.umd.min.js\\\"></script>\n<style>\n.chart-widget{\n    background:#fff;\n    border-radius:12px;\n    padding:20px;\n    box-shadow:0 2px 8px rgba(0,0,0,0.1);\n    max-width:800px;\n    margin:20px auto;\n    direction:rtl;\n}\n.chart-title{\n    text-align:center;\n    color:#1e293b;\n    font-size:18px;\n    font-weight:600;\n    margin-bottom:15px;\n}\n.chart-widget canvas{\n    width:100% !important;\n    height:300px !important;\n}\n</style>\n\n<div class=\\\"chart-widget\\\">\n    <div class=\\\"chart-title\\\">عدد الفئات حسب الوقت المفضل</div>\n    <canvas id=\\\"barChart\\\"></canvas>\n</div>\n\n<div class=\\\"chart-widget\\\">\n    <div class=\\\"chart-title\\\">نسبة الفئات حسب الوقت المفضل</div>\n    <canvas id=\\\"doughnutChart\\\"></canvas>\n</div>\n\n<script>\nconst labels = [\\\"من 4م الى 9م\\\",\\\"من 8ص الى 4 م\\\",\\\"من 9م الى 4 ص\\\"];\nconst counts = [254,73,45];\nconst percentages = [68.2795698925,19.623655914,12.0967741935];\nnew Chart(document.getElementById('barChart').getContext('2d'),{\n    type:'bar',\n    data:{\n        labels:labels,\n        datasets:[{\n            label:'عدد',\n            data:counts,\n            backgroundColor:['#3b82f6','#10b981','#f59e0b'],\n            borderRadius:6\n        }]\n    },\n    options:{\n        indexAxis:'y',\n        responsive:true,\n        maintainAspectRatio:false,\n        plugins:{\n            legend:{display:false},\n            tooltip:{\n                callbacks:{\n                    label:function(context){\n                        return context.dataset.label+': '+context.parsed.x;\n                    }\n                }\n            }\n        },\n        scales:{\n            x:{beginAtZero:true}\n        }\n    }\n});\nnew Chart(document.getElementById('doughnutChart').getContext('2d'),{\n    type:'doughnut',\n    data:{\n        labels:labels,\n        datasets:[{\n            data:percentages,\n            backgroundColor:['#3b82f6','#10b981','#f59e0b'],\n            borderWidth:2,\n            borderColor:'#fff'\n        }]\n    },\n    options:{\n        responsive:true,\n        maintainAspectRatio:false,\n        plugins:{\n            legend:{position:'bottom'},\n            tooltip:{\n                callbacks:{\n                    label:function(context){\n                        return context.label+': '+context.parsed.toFixed(2)+'%';\n                    }\n                }\n            }\n        }\n    }\n});\n</script>"
}

# Decode the string (JSON-like escaping)
chart_html = data["chart_html"].encode().decode("unicode_escape")

print(chart_html)
